export const adminSettingsTranslations = {
  en: {
    title: 'System Settings',
    subtitle: 'Configure portal settings and manage system preferences',
    profile: 'Profile Settings',
    notifications: 'Notification Settings',
    system: 'System Configuration',
    security: 'Security Settings',
    portal: 'Portal Configuration',
    users: 'User Management',
    personalInfo: 'Personal Information',
    changePassword: 'Change Password',
    name: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    position: 'Position',
    department: 'Department',
    bio: 'Bio',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    emailAlerts: 'Email Alerts',
    smsAlerts: 'SMS Alerts',
    systemAlerts: 'System Alerts',
    maintenanceAlerts: 'Maintenance Alerts',
    autoBackup: 'Automatic Backup',
    maintenanceMode: 'Maintenance Mode',
    debugMode: 'Debug Mode',
    apiRateLimit: 'API Rate Limit (per hour)',
    sessionTimeout: 'Session Timeout (minutes)',
    siteName: 'Site Name',
    supportEmail: 'Support Email',
    supportPhone: 'Support Phone',
    maintenanceMessage: 'Maintenance Message',
    maxFileSize: 'Max File Size (MB)',
    allowedFileTypes: 'Allowed File Types',
    save: 'Save Changes',
    cancel: 'Cancel',
    edit: 'Edit',
    saveProfile: 'Save Profile',
    adminUsers: 'Administrator Users',
    addUser: 'Add User',
    userName: 'User Name',
    userEmail: 'Email',
    role: 'Role',
    status: 'Status',
    actions: 'Actions',
    active: 'Active',
    inactive: 'Inactive',
    superAdmin: 'Super Admin',
    deptAdmin: 'Department Admin',
    regionalAdmin: 'Regional Admin',
    lastLogin: 'Last Login',
    created: 'Created',
    systemHealth: 'System Health',
    databaseStatus: 'Database Status',
    serverStatus: 'Server Status',
    backupStatus: 'Backup Status',
    healthy: 'Healthy',
    warning: 'Warning',
    error: 'Error'
  },
  hi: {
    title: 'सिस्टम सेटिंग्स',
    subtitle: 'पोर्टल सेटिंग्स कॉन्फ़िगर करें और सिस्टम प्राथमिकताएं प्रबंधित करें',
    profile: 'प्रोफ़ाइल सेटिंग्स',
    notifications: 'अधिसूचना सेटिंग्स',
    system: 'सिस्टम कॉन्फ़िगरेशन',
    security: 'सुरक्षा सेटिंग्स',
    portal: 'पोर्टल कॉन्फ़िगरेशन',
    users: 'उपयोगकर्ता प्रबंधन',
    personalInfo: 'व्यक्तिगत जानकारी',
    changePassword: 'पासवर्ड बदलें',
    name: 'पूरा नाम',
    email: 'ईमेल पता',
    phone: 'फोन नंबर',
    position: 'पद',
    department: 'विभाग',
    bio: 'बायो',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    emailAlerts: 'ईमेल अलर्ट',
    smsAlerts: 'SMS अलर्ट',
    systemAlerts: 'सिस्टम अलर्ट',
    maintenanceAlerts: 'रखरखाव अलर्ट',
    autoBackup: 'स्वचालित बैकअप',
    maintenanceMode: 'रखरखाव मोड',
    debugMode: 'डिबग मोड',
    apiRateLimit: 'API दर सीमा (प्रति घंटा)',
    sessionTimeout: 'सत्र समाप्ति (मिनट)',
    siteName: 'साइट का नाम',
    supportEmail: 'सहायता ईमेल',
    supportPhone: 'सहायता फोन',
    maintenanceMessage: 'रखरखाव संदेश',
    maxFileSize: 'अधिकतम फ़ाइल आकार (MB)',
    allowedFileTypes: 'अनुमतित फ़ाइल प्रकार',
    save: 'परिवर्तन सहेजें',
    cancel: 'रद्द करें',
    edit: 'संपादित करें',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    adminUsers: 'प्रशासक उपयोगकर्ता',
    addUser: 'उपयोगकर्ता जोड़ें',
    userName: 'उपयोगकर्ता नाम',
    userEmail: 'ईमेल',
    role: 'भूमिका',
    status: 'स्थिति',
    actions: 'कार्य',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    superAdmin: 'सुपर एडमिन',
    deptAdmin: 'विभाग एडमिन',
    regionalAdmin: 'क्षेत्रीय एडमिन',
    lastLogin: 'अंतिम लॉगिन',
    created: 'बनाया गया',
    systemHealth: 'सिस्टम स्वास्थ्य',
    databaseStatus: 'डेटाबेस स्थिति',
    serverStatus: 'सर्वर स्थिति',
    backupStatus: 'बैकअप स्थिति',
    healthy: 'स्वस्थ',
    warning: 'चेतावनी',
    error: 'त्रुटि'
  }
};

export const demoAdminUsers = [
  {
    id: 1,
    name: { en: 'Arvind Gupta', hi: 'अरविंद गुप्ता' },
    email: 'admin.super@delhi.gov.in',
    role: 'Super Admin',
    status: 'Active',
    lastLogin: '2024-01-20 09:30',
    created: '2024-01-01',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face'
  },
  {
    id: 2,
    name: { en: 'Preeti Singh', hi: 'प्रीति सिंह' },
    email: 'admin.dept@delhi.gov.in',
    role: 'Department Admin',
    status: 'Active',
    lastLogin: '2024-01-19 14:22',
    created: '2024-01-05',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b1a2?w=40&h=40&fit=crop&crop=face'
  },
  {
    id: 3,
    name: { en: 'Mohit Sharma', hi: 'मोहित शर्मा' },
    email: 'admin.regional@delhi.gov.in',
    role: 'Regional Admin',
    status: 'Inactive',
    lastLogin: '2024-01-15 16:45',
    created: '2024-01-10',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face'
  }
];

export const defaultSettings = {
  notifications: {
    emailAlerts: true,
    smsAlerts: false,
    systemAlerts: true,
    maintenanceAlerts: true
  },
  system: {
    autoBackup: true,
    maintenanceMode: false,
    debugMode: false,
    apiRateLimit: '1000',
    sessionTimeout: '30'
  },
  portal: {
    siteName: 'Vyapaar सारथी',
    supportEmail: 'admin@delhi.gov.in',
    supportPhone: '+91-11-23456789',
    maintenanceMessage: 'System under maintenance. Please try again later.',
    maxFileSize: '10',
    allowedFileTypes: 'PDF, JPG, PNG, DOC'
  }
};